os: windows
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T homework_win-0.0.$TRAVIS_BUILD_NUMBER-win -uattamayte:$BINTRAY_API_KEY "https://api.bintray.com/content/attamayte/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/homework_win-0.0.$TRAVIS_BUILD_NUMBER-win;publish=1"
